config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :locations, only: [:show]

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, presence: true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  acts_as_paranoid

  include Redis::Objects
  counter :viewed_count

  as_enum :gender, [:not_available, :male, :female], map: :string, source: :gender

  as_enum :status, [:initial, :referred, :treatment, :closed], map: :string, source: :status

  validates :first_name, :last_name, :status, :location, presence: true
  validates :gender, inclusion: {in: [:not_available, :male, :female]}
  validates :status, inclusion: {in: [:initial, :referred, :treatment, :closed]}

  belongs_to :location

  scope :onTreatment, -> { where(status: 'treatment') }

  def mr
    "MR0000#{id}"
  end

  def full_name
    [first_name, middle_name, last_name].compact.join('.')
  end

  def age
    now = Time.now.utc.to_date
    diff = (now.month > date_of_birth.month || (now.month == date_of_birth.month && now.day >= date_of_birth.day)) ? 0 : 1
    now.year - date_of_birth.year - diff
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :set_locale
  protect_from_forgery with: :exception

  def set_locale
    if params[:locale] && I18n.available_locales.include?(params[:locale].to_sym)
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show]

  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient.viewed_count.incr
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :middle_name, :date_of_birth, :gender, :location_id, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patients</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "中文版", :controller => controller.controller_name,
            :action => controller.action_name, :locale => "zh-CN"	%>
<%= link_to "English", :controller => controller.controller_name,
            :action => controller.action_name, :locale => "en" %>

<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/locations/show.html.erb
<h1><%= t 'location'%></h1>
<p>
  <strong><%= t 'location_name'%>:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @location.code %>
</p>

app/views/patients/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= form_for(@patient) do |f| %>
        <% if @patient.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

              <ul>
                <% @patient.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :first_name, t('first_name') %><br>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :middle_name, t('middle_name') %><br>
          <%= f.text_field :middle_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, t('last_name') %><br>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :date_of_birth, t('birthday') %><br>
          <%= f.date_select :date_of_birth, start_year: 1900 %>
        </div>
        <div class="form-group">
          <%= f.radio_button :gender, 'not_available' %>
          <%= f.label :gender, t('not_available'), :value => 'not_available' %>
          <%= f.radio_button :gender, 'male' %>
          <%= f.label :gender, t('male'), :value => 'male' %>
          <%= f.radio_button :gender, 'female' %>
          <%= f.label :gender, t('female'), :value => 'female' %>
        </div>

        <div class="form-group">
          <%= f.label :location_id, t('location') %><br>
          <%= f.collection_select(:location_id, Location.all, :id, :name) %>
        </div>

        <div class="form-group">
          <%= f.label :status, t('status') %><br>
          <%= f.select(:status, options_for_select([[t('initial'), 'initial'], [t('referred'), 'referred'],[t('treatment'), 'treatment'], [t('closed'), 'closed']], selected: @patient.status)) %>
        </div>

        <button type="submit" class="btn btn-default"><%= t 'submit'%></button>
    <% end %>
  </div>
</div>

app/views/patients/edit.html.erb
<h1><%= t 'edit' %></h1>

<%= render 'form' %>

<%= link_to t('show'), @patient %> |
<%= link_to t('back'), patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'listing_patients'  %></h1>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading ">
    <h3 class="panel-title"><%= t 'patients_list' %></h3>
  </div>

  <div class="panel panel-body">
    <!-- Table -->
    <table class="table table-hover">
      <thead>
      <tr>
        <th><%= t 'mr' %></th>
        <th><%= t 'full_name' %></th>
        <th><%= t 'age' %></th>
        <th><%= t 'gender' %></th>
        <th><%= t 'status' %></th>
        <th><%= t 'location' %></th>
        <th><%= t 'viewed_count' %></th>
        <th colspan="3"><%= t 'actions' %></th>
      </tr>
      </thead>

      <tbody>
      <% @patients.each do |patient| %>
          <tr>
            <td><%= patient.mr %></td>
            <td><%= patient.full_name %></td>
            <td><%= patient.age %></td>
            <td><%= t("#{patient.gender.downcase}") %></td>
            <td><%= t("#{patient.status.downcase}")%></td>
            <td><%= patient.location.name %></td>
            <td><%= patient.viewed_count.value %></td>
            <td><%= link_to t('show'), patient %></td>
            <td><%= link_to t('edit'), edit_patient_path(patient) %></td>
            <td><%= link_to t('destroy'), patient, method: :delete, data: {confirm: t('confirm')} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to t('new_patient'), new_patient_path %>

app/views/patients/new.html.erb
<h1><%= t 'new_patient' %></h1>


<%= render 'form' %>


<%= link_to t('back'), patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t 'first_name' %>:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong><%= t 'middle_name' %>:</strong>
  <%= @patient.middle_name %>
</p>

<p>
  <strong><%= t 'last_name' %>:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong><%= t 'birthday' %>:</strong>
  <%= @patient.date_of_birth %>
</p>

<p>
  <strong><%= t 'gender' %>:</strong>
  <%= t("#{@patient.gender.downcase}") %>
</p>

<p>
  <strong><%= t 'status' %>:</strong>
  <%= t("#{@patient.status.downcase}") %>
</p>

<p>
  <strong><%= t 'location' %>:</strong>
  <%= link_to @patient.location.name, @patient.location %>
</p>

<%= link_to t('edit'), edit_patient_path(@patient) %> |
<%= link_to t('back'), patients_path %>